# Generated by Django 6.0.1 on 2026-02-11 17:46

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_content_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=post.models.post_id_creation, max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=post.models.post_id_creation, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
