# Generated by Django 6.0.1 on 2026-02-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_post_id_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
