# Generated by Django 6.0.1 on 2026-02-19 16:54

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_image'),
    ]

    operations = [TrigramExtension()
    ]
