# Generated by Django 6.0.1 on 2026-02-11 20:57

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.IntegerField(default=user.models.generate_uid, editable=False, unique=True),
        ),
    ]
