# Generated by Django 6.0.1 on 2026-02-11 21:13

from django.db import migrations
import user.models
import random


def populate_uid(apps, schema_editor):
    Profile = apps.get_model('user', 'Profile')
    used_uids = set()
    
    for profile in Profile.objects.all():
        if not profile.uid or profile.uid in used_uids:
            while True:
                uid = random.randint(10000000, 99999999)
                if uid not in used_uids:
                    profile.uid = uid
                    used_uids.add(uid)
                    break
            profile.save()
        else:
            used_uids.add(profile.uid)


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_uid'),
    ]

    operations = [
        migrations.RunPython(populate_uid, reverse_populate),
    ]
